<!-- Page Title -->
<?php
$id = $this->getRequest()->getParam('id');
$model = Mage::getModel('test/test');
?>
<form action="<?php echo Mage::getUrl('test/index/save') ?>" method="post">
<?php if($id>0):?>
  <?php $model->load($id);?>
  <input type="hidden" name="id" value="<?php echo $id?>">
<?php endif;?>
  <fieldset>
    <ul>
     <li>
       <label for="nom">First</label>
       <input type="text" id="nom" name="nom" value="<?php echo $model->getNom();?>"/>
     </li>
     <li>
         <label for="prenom">Last</label>
         <input type="text" id="prenom" name="prenom" value="<?php echo $model->getPrenom();?>"/>
     </li>
     <li>
        <label for="nom">Telephone</label>
        <input type="text" id="telephone" name="telephone" value="<?php echo $model->getTelephone();?>"/>
    </li>
     <li>
        <input type="submit" value="Save" />
    </li>
  </ul>
 </fieldset>
</form>

<div class="page-title">
<h2><?php echo $this->__('Address Book') ?></h2>
</div>
<table id="my-person-table" class="data-table">
<colgroup>
<col width="1">
<col>
<col>
<col>
<col>
</colgroup>
<thead>
<tr class="first last">
<th><?php echo $this->__('ID')?></th>
<th><?php echo $this->__('First')?></th>
<th><?php echo $this->__('Last')?></th>
<th><?php echo $this->__('Telephone')?></th>
<th>Action</th>
</tr>
</thead>
<tbody>
<?php foreach($this->getCollection() as $person): ?>
<tr>
<td><?php echo $person->getData('id_pfay_test')?></td>
<td><?php echo $person->getData('nom')?></td>
<td><?php echo $person->getData('prenom')?></td>
<td><?php echo $person->getData('telephone')?></td>
<td><a href="<?php echo $this->getUrl('test/index/index', array('id' => $person->getId()));?>">Edit</a> / <a href="<?php echo $this->getUrl('test/index/delete', array('id' => $person->getId()));?>">Delete</a></td>
</tr>
<?php endforeach ?>
</tbody>
</table>
